title: RPI-IEEE
email: ieee.rpi.officers@gmail.com
description: RPI-IEEE is the IEEE Student Branch at Rensselaer Polytechnic Institute.
baseurl: /ieee
url: 'https://www.ecse.rpi.edu/ieee'
twitter_username: ''
github_username: ''
markdown: kramdown
theme: minima
excerpt_separator: "<!--excerpt-->"
plugins:
  - jekyll-feed
